---
- hosts: all
  remote_user: root
  sudo: yes
  tasks:
    - name: make sure you have curl
      apt: name=curl state=present
    
    - name: execute official PPA setting script
      shell: "sudo curl -sL https://deb.nodesource.com/setup | sudo bash - executable=/bin/bash"
    
    - name: install nodejs
      apt: name=nodejs state=present
    
    - name: install build-essential
      apt: name=build-essential state=present
